name: Frontend Deployment - DEV

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  HOST: ${{ vars.HOST_NAME_dev }}
  USERNAME: ${{ vars.USER_NAME_dev }}
  PORT: 22
  NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}
  NEXT_PUBLIC_DOMAIN: ${{ vars.NEXT_PUBLIC_DOMAIN }}

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: build-npm
        run: |
          cd ./frontend
          npm ci
          npm run build
          ls -la
          pwd
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ env.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_DOMAIN: ${{ env.NEXT_PUBLIC_DOMAIN }}

      - name: create tar
        run: |
          cd ./frontend
          tar -czf ../frontend.tar .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-tar
          path: ./frontend.tar

  Upload-Run:
    runs-on: self-hosted
    needs: Build
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-tar
          path: ./

      - name: copy tar build via ssh
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.VM_KEY_dev }}
          port: ${{ env.PORT }}
          source: "./frontend.tar"
          target: /home/admin_user/apps/

      - name: copy script via ssh
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.VM_KEY_dev }}
          port: ${{ env.PORT }}
          source: scripts/run-app.sh
          target: /home/admin_user/apps/

      - name: Run artifact
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.VM_KEY_dev }}
          port: ${{ env.PORT }}
          command_timeout: 350s
          script: bash /home/admin_user/apps/scripts/run-app.sh fe
